[project]
name = "mcp-lsp-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp==1.3.0",
    "multilspy==0.0.12",
]

[tool.uv.sources]
multilspy = { path = "projects/multilspy" }
